version: '3.7'
services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile.local
        container_name: tzs_app
        volumes:
            - .:/var/www/html/erdert
            - .env.production:/var/www/html/erdert/.env
        labels:
            - 'traefik.http.routers.backend.rule=Host(`erdert.dndnew.hu`)'
            # - 'traefik.http.routers.backend.rule=(Host(`backend.localhost`) && PathPrefix(`/api`))' if you want to use /api as prefix
        ports:
            - '8000:8000'
        env_file:
            - .env.production
        networks:
            - traefik-public
        command: sh -c 'npm install && composer install && php artisan serve --host 0.0.0.0 && npm run watch'
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: tzs_db
        restart: unless-stopped
        env_file: ./mysql.env
        ports:
            - '3307:3306'
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - traefik-public
networks:
    traefik-public:
        external: true
