version: '3.7'
services:
    backend:
        platform: linux/arm64/v8
        build:
            context: ./
            dockerfile: Dockerfile.local
        volumes:
            - .:/var/www/html/backend
            - .env:/var/www/html/backend/.env
        ports:
            - '8000:8000'
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - laravel
        depends_on:
            - mysql
        container_name: tzs_app
        command: php artisan serve --host 0.0.0.0
    mysql:
        image: mysql
        platform: linux/arm64 #this will need to solve problem on M1 chip MAC
        container_name: tzs_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'tuzser_backend'
            # MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3307:3306'
        volumes:
            - 'mysql8:/var/lib/mysql'
        networks:
            - laravel
    nginx:
        image: nginx
        container_name: tzs_nginx
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html/backend
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
    traefik:
        image: traefik:v2.0
        container_name: tzs_traefik
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
            # - '--entrypoints.websecure.address=:443'
            # - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
        ports:
            # - '80:80'
            - '8080:8080'
            # - '443:443'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.api.rule=Host(`traefik.tuzser.com`)'
            # - 'traefik.http.router.traefik.entrypoints=websecure'
            - 'traefik.http.routers.api.service=api@internal'
            # - 'traefik.http.routers.traefik.tls.certresolver=myresolver'
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    mysql8:
        driver: local
